### ISSUE TITLE
Convert to next/script

### ISSUE THREAD

**Issue by dferber90** [simpleanalytics/next-js-app#11]
Hi Adriaan,

I wanted to give a heads-up that it's no longer necessary to use `_document` to set up scripts.

As of Next.js 11 there is a new [Script Component](https://nextjs.org/docs/basic-features/script) that can be placed inside of `_app` to load the script.

This is how I've configured Simple Analytics in my Next.js application:

```tsx
// _app.tsx
import type { AppProps } from "next/app";
import React from "react";
import Script from "next/script";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <React.Fragment>
      <Component {...pageProps} />
      <Script src="https://scripts.simpleanalyticscdn.com/latest.js" />
      <noscript>
        {/* eslint-disable @next/next/no-img-element */}
        <img
          src="https://sa.dferber.de/noscript.gif"
          alt=""
          referrerPolicy="no-referrer-when-downgrade"
        />
      </noscript>
    </React.Fragment>
  );
}
export default MyApp;
```

This will use the `afterInteractive` strategy to load the script. From the docs:

> For scripts that can fetch and execute after the page is interactive, such as tag managers and analytics. These scripts are injected on the client-side and will run after hydration.

Of course the old way still works as well :)

Best,
Dom

**Comment by adriaanvanrossum** [comment]
This is a coincidence. We just copied your code example to our install docs!

https://docs.simpleanalytics.com/install-simple-analytics-with-next

**Comment by dferber90** [comment]
Nice! I was just going through my old issues and closing some of them, this happened to be one of them :P
